# Uses variables from .env
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"
    env_file:
      - ./packages/db/.env          # ✅ Load the real env values
    depends_on:
      - postgres

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    env_file:
      - ./packages/db/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_HTTP_BACKEND=http://backend:3001
      - NEXT_PUBLIC_WS_URL=ws://ws:8080
    depends_on:
      - backend
      - ws

volumes:
  postgres_data: